"""create movie explorer tables

Revision ID: b67c2823db7d
Revises: 0603f8112de5
Create Date: 2026-01-15 21:52:14.931487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b67c2823db7d'
down_revision: Union[str, Sequence[str], None] = '0603f8112de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('genres', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('genres', sa.Column('slug', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_genres_slug'), 'genres', ['slug'], unique=True)
    op.add_column('movies', sa.Column('release_year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_year')
    op.drop_index(op.f('ix_genres_slug'), table_name='genres')
    op.drop_column('genres', 'slug')
    op.drop_column('genres', 'description')
    op.drop_table('movie_reviews')
    # ### end Alembic commands ###
