"""create movie explorer tables

Revision ID: d2374a9deec6
Revises: 871596a3dbda
Create Date: 2026-01-17 11:12:28.289780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2374a9deec6'
down_revision: Union[str, Sequence[str], None] = '871596a3dbda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actors_name'), 'actors', ['name'], unique=False)
    op.create_index(op.f('ix_directors_name'), 'directors', ['name'], unique=False)
    op.drop_constraint(op.f('genres_name_key'), 'genres', type_='unique')
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_movie_reviews_movie_id'), 'movie_reviews', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movies_director_id'), 'movies', ['director_id'], unique=False)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_director_id'), table_name='movies')
    op.drop_index(op.f('ix_movie_reviews_movie_id'), table_name='movie_reviews')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.create_unique_constraint(op.f('genres_name_key'), 'genres', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_directors_name'), table_name='directors')
    op.drop_index(op.f('ix_actors_name'), table_name='actors')
    # ### end Alembic commands ###
